const songs = [
    { title: "First Person Shooter", artist: "Drake", vibe: ["Hard", "Engaging"] },
    { title: "Million Dollar Baby", artist: "Tommy Richman", vibe: ["Hard", "Engaging"] },
    { title: "Money So Big", artist: "Yeat", vibe: ["Hard", "Engaging"] },
    { title: "Vampire Heart", artist: "", vibe: ["Hard", "Engaging"] },
    { title: "Space Cadet", artist: "Metro Boomin", vibe: ["Hard", "Engaging"] },
    { title: "Like That", artist: "Metro Boomin, Future", vibe: ["Hard", "Engaging"] },
    { title: "Surround Sound", artist: "J.I.D", vibe: ["Hard", "Engaging"] },
    { title: "Yale", artist: "Ken Carson", vibe: ["Hard", "Engaging"] },
    { title: "Walk Em Down", artist: "Metro Boomin", vibe: ["Hard", "Engaging"] },
    { title: "Another Late Night", artist: "Drake", vibe: ["Chill", "Engaging"] },
    { title: "Heart On My Sleeve", artist: "Al Drake", vibe: ["Chill", "Engaging"] },
    { title: "Rapp Snitch Knishes", artist: "MF Doom", vibe: ["Chill", "Engaging"] },
    { title: "Tell Em (slowed + reverb)", artist: "Cochise", vibe: ["Chill", "Engaging"] },
    { title: "Swag Overload", artist: "Ken Carson", vibe: ["Chill", "Engaging"] },
    { title: "Bigger Than Everything", artist: "Yeat", vibe: ["Chill", "Engaging"] },
    { title: "Private Jet", artist: "D Savage", vibe: ["Chill", "Engaging"] },
    { title: "Low Key Gliding", artist: "Hal Walker", vibe: ["Chill", "Engaging"] },
    { title: "Hell N Back", artist: "Bakar", vibe: ["Chill", "Engaging"] },
    { title: "In Ha Mood", artist: "Ice Spice", vibe: ["GirlyPop", "Engaging"] },
    { title: "HOME (slowed + reverb)", artist: "resonance", vibe: ["Emotional", "Inspirational"] },
    { title: "Another Love", artist: "Tom Odell", vibe: ["Emotional"] },
    { title: "1901", artist: "Phoenix", vibe: ["Inspirational"] },
    { title: "After Hours (slowed + reverb)", artist: "The Weeknd", vibe: ["Inspirational"] },
    { title: "Memory Reboot", artist: "VØJ, Narvent", vibe: ["Inspirational"] },
    { title: "Righteous", artist: "Mo Beats", vibe: ["Inspirational"] },
    { title: "plage coquillage (kiss song) best part only", artist: "", vibe: ["Thought-provoking", "Inspirational"] },
    { title: "Echo Sax End", artist: "", vibe: ["Thought-provoking", "Inspirational"] },
    { title: "Test & Recognize", artist: "Flume", vibe: ["Thought-provoking", "Inspirational"] },
    { title: "Dragonfly", artist: "Dana and Alden", vibe: ["Thought-provoking", "Inspirational"] },
    { title: "Mr. Blindbandit - Suspense, Horror, Piano and M", artist: "Mr. Blindbandit", vibe: ["Thought-provoking", "Suspense"] },
    { title: "i was only temporary - my head is empty", artist: "", vibe: ["Thought-provoking", "Suspense"] },
    { title: "Øfdream - Thelema", artist: "Øfdream", vibe: ["Thought-provoking"] },
    { title: "Else - Paris", artist: "Else", vibe: ["Thought-provoking"] },
    { title: "Luminary", artist: "Joel Sunny", vibe: ["Thought-provoking"] },
    { title: "Blade Runner 2049 - Synthwave Goose", artist: "Synthwave Goose", vibe: ["Thought-provoking"] },
    { title: "The Lost Soul Down (Slowed & Reverb)", artist: "", vibe: ["Thought-provoking", "Sigma"] },
    { title: "Call me (Slowed)", artist: "", vibe: ["Sigma"] },
    { title: "After Dark", artist: "Mr.Kitty", vibe: ["Sigma"] },
    { title: "Bloody Mary Remix", artist: "", vibe: ["Sigma"] },
    { title: "Sahara", artist: "Hensonn", vibe: ["Sigma"] },
    { title: "particles (slowed)", artist: "villiam lane", vibe: ["Sigma"] },
    { title: "METAMORPHOSIS", artist: "Interworld", vibe: ["Phonk"] },
    { title: "GigaChad Theme", artist: "g3ox_em", vibe: ["Phonk"] },
    { title: "Dream Space", artist: "DVRST", vibe: ["Phonk"] },
    { title: "ESSENCE", artist: "Casper", vibe: ["Phonk"] },
    { title: "Close Eyes (slowed + reverb)", artist: "DVRST", vibe: ["Phonk"] },
    { title: "Suicide Year", artist: "weedmane", vibe: ["Phonk"] },
    { title: "Money is for the Rent - Not For The Soul", artist: "Mr. Carmack", vibe: ["idek i just think this is sick"] },
  ];
  